- name: Install ufw
  become: yes
  apt:
    name: ufw
    state: installed

- name: Allow SSH access to logserver
  ufw:
    rule: allow
    proto: tcp
    from_ip: any
    port: 22
  notify: restart ufw

- name: Allow access
  ufw:
    rule: allow
    delete: no
    proto: any
    port: "{{ item.port }}"
    from: "{{ item.from }}"
    to: "{{ item.to }}"
  notify: restart ufw
  with_items:
     - { port: 3306, from: 192.168.1.27, to: 192.168.1.22 }
     - { port: 3306, from: 192.168.1.28, to: 192.168.1.22 }  

- name: Deny access
  ufw:
    rule: deny
    delete: no
    proto: any
  notify: restart ufw

- name: Start ufw service
  service:
    name: ufw
    state: restarted
    enabled: yes

- name: Enable ufw functionality
  ufw:
    state: enabled
