- name: Install tools
  apt: name={{item}} state=present
  with_items:
    - python-mysqldb
    - python3-mysqldb

- name: Install pip
  apt:
    name: python-pip
    state: present

- name: install mysql-server
  apt: name=mysql-server state=present
 
- name: Ensure mysql started
  service: name=mysql state=started enabled=yes
